import hashlib
import time
from datetime import datetime
from typing import Dict, Any

def generate_forensic_report(analysis_record: Dict[str, Any]) -> Dict[str, Any]:
    """
    Assembles a digital forensics grade report with tamper-evident cryptographic hash.
    """
    analysis_id = analysis_record.get("id", f"dfs_{int(time.time())}")
    timestamp_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Compute SHA-256 hash of core forensic metrics for chain-of-custody verification
    hash_payload = f"{analysis_id}:{analysis_record.get('filename')}:{analysis_record.get('verdict')}:{analysis_record.get('probability')}"
    sha256_hash = hashlib.sha256(hash_payload.encode("utf-8")).hexdigest()

    report_id = f"DFS-REP-{datetime.utcnow().year}-{analysis_id[-6:].upper()}"

    return {
        "report_id": report_id,
        "platform_name": "DeepFakeShield AI Media Forensics",
        "generated_at": timestamp_str,
        "verification_hash": sha256_hash,
        "file_information": {
            "filename": analysis_record.get("filename", "unknown_file"),
            "media_type": analysis_record.get("media_type", "image").upper(),
            "file_size": analysis_record.get("file_size_bytes", 0),
            "sha256": sha256_hash[:16] + "..." + sha256_hash[-16:],
        },
        "verdict_summary": {
            "verdict": analysis_record.get("verdict", "UNCERTAIN"),
            "deepfake_probability": analysis_record.get("probability", 0.0),
            "authenticity_confidence": analysis_record.get("confidence", 0.0),
            "model_identifier": analysis_record.get("model_name", "ForensicEngine-v2"),
            "model_version": analysis_record.get("model_version", "2.0.0"),
            "processing_time_ms": analysis_record.get("processing_time_ms", 0.0)
        },
        "technical_analysis": analysis_record.get("metadata_json", {}),
        "explainability": analysis_record.get("explainability_json", {}),
        "chain_of_custody": {
            "intake_protocol": "NIST SP 800-86 Digital Evidence Guidelines",
            "integrity_status": "Verified / Tamper-evident",
            "analyst_id": "DFS-AUTOMATED-FORENSIC-SYSTEM"
        },
        "legal_disclaimer": "AI-generated media detection is probabilistic. Results should be interpreted as forensic indicators rather than definitive proof. This report is generated by DeepFakeShield automated forensic models."
    }
